/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Sep 15 09:42:54 2016. */

#include "cjtx.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t state_request_fields[14] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, state_request, id, id, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, state_request, longitude, id, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, state_request, latitude, longitude, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, state_request, pressure1, latitude, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, state_request, pressure2, pressure1, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, state_request, pressure3, pressure2, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, state_request, temperature1, pressure3, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, state_request, temperature2, temperature1, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, state_request, temperature3, temperature2, 0),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, state_request, speed, temperature3, 0),
    PB_FIELD( 11, UINT32  , OPTIONAL, STATIC  , OTHER, state_request, timestamp, speed, 0),
    PB_FIELD( 12, INT32   , OPTIONAL, STATIC  , OTHER, state_request, engine_speed, timestamp, 0),
    PB_FIELD( 13, UINT32  , OPTIONAL, STATIC  , OTHER, state_request, mileage, engine_speed, 0),
    PB_LAST_FIELD
};

const pb_field_t extinfo_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, extinfo, set_interval, set_interval, 0),
    PB_FIELD(  2, BOOL    , OPTIONAL, STATIC  , OTHER, extinfo, upload_info, set_interval, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, extinfo, need_upgrade, upload_info, 0),
    PB_LAST_FIELD
};

const pb_field_t state_response_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, state_response, errcode, errcode, 0),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, state_response, extinfo, errcode, &extinfo_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(state_response, extinfo) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_state_request_extinfo_state_response)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(state_response, extinfo) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_state_request_extinfo_state_response)
#endif


/* @@protoc_insertion_point(eof) */
